---
title: "Assignment4_Lobsters"
author: "Robert Saldivar"
date: "November 13, 2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
#1. Loading Packages and csv files

library(tidyverse)
library(RColorBrewer)
library(ggpubr)
library(knitr)
library(effsize)
library(pwr)
library(extrafont)
library(plotly)
library(ggrepel)
library(kableExtra)
library(onewaytests)
library(car)
library(vcdExtra) #for getting the data into case format
library(xtable)
library(FSA)
library(ggsignif) #to add significance brackets

lobster_size <- read_csv("lobster_size_abundance.csv")
lobster_traps <- read_csv("lobster_traps.csv")
```

```{r, include=FALSE}
#2 Initial Data Editing
lobster_size_edits <- lobster_size %>%
  filter(SIZE !=-99999) %>%
  select(YEAR, SITE, SIZE, COUNT) # Edit Lobster Size data to remove -99999 data from size column and remove transect information
  

lobster_traps_edits <- lobster_traps %>%
  filter(SITE=="AQUE" |SITE =="NAPL" |SITE=="MOHK" |SITE=="IVEE" |SITE=="CARP") %>%
  select(YEAR, SITE, TRAPS)

```

```{r, include=FALSE}
#3 checking data for normality

lobster_size_hist <- ggplot(lobster_size_edits, aes(x=SIZE)) +
  geom_histogram() +
  facet_wrap(~SITE)

lobster_size_hist

lobster_size_qq <- ggplot(lobster_size_edits, aes(sample=SIZE)) +
  geom_qq() +
  facet_wrap(~SITE)

lobster_size_qq

lobster_traps_hist <- ggplot(lobster_traps_edits, aes(x=TRAPS)) +
  geom_histogram() +
  facet_wrap(~SITE)

lobster_traps_hist

lobster_traps_qq <- ggplot(lobster_traps_edits, aes(sample=TRAPS)) +
  geom_qq() +
  facet_wrap(~SITE)

lobster_traps_qq
```

```{r, echo=FALSE, message=FALSE}
#4 create graphs of abundance and fishing pressure from 2012-2017

abundance_col <- ggplot(lobster_size_edits, aes(x=YEAR, y=COUNT)) +
  geom_col(aes(fill=SITE), show.legend=FALSE) +
  facet_wrap(~SITE) +
  theme_classic() +
  ggtitle("Lobster Abundance") +
  labs(x="Year", y="count")

abundance_col

fishing_pressure_col <- ggplot(lobster_traps_edits, aes(x=YEAR, y=TRAPS)) +
  geom_col(aes(fill=SITE), show.legend=FALSE) +
  facet_wrap(~SITE) +
  theme_classic() +
  ggtitle("Fishing Pressure") +
  labs(x="Year", y="Number of Traps")

fishing_pressure_col
```

```{r, include=FALSE}
#5 put lobster size data into case format.

lobster_case_format2017 <- lobster_size_edits %>%
  filter(YEAR=="2017") %>%
  as.data.frame() %>%
  expand.dft(freq="COUNT")
```

```{r, echo=FALSE}
#Create Datea table for 2012 and 2017
lobster_case_format2012 <- lobster_size_edits %>%
  filter(YEAR=="2012") %>%
  as.data.frame() %>%
  expand.dft(freq="COUNT")

lobster_size_summary2012 <- lobster_case_format2012 %>%
  group_by(SITE) %>%
  summarize(
    lobster_mean = round(mean(SIZE),2),
    lobster_sd = round(sd(SIZE),2),
    sample_size = length(SIZE)
  )

Table2012 <- kable(lobster_size_summary2012, col.names= c("Site", "Mean Lobster Size (mm)", "Standard Deviation of Size (mm)", "Abundance"))
Table2012

```

```{r, echo=FALSE}
#6 run significance tests for lobster size
lobster_levene <- leveneTest(SIZE~SITE, data=lobster_case_format2017)
lobster_levene
#Variences are not equal check to see if another need to do another test beside anova

lobster_aov <- aov(SIZE~SITE, data=lobster_case_format2017)
summary(lobster_aov)

lobster_tukeys <- TukeyHSD(lobster_aov)
lobster_tukeys
```

```{r, echo=FALSE, message=FALSE}
#7 Creating Graph and table from anova data


lobster_size_summary2017 <- lobster_case_format2017 %>%
  group_by(SITE) %>%
  summarize(
    lobster_mean = round(mean(SIZE),2),
    lobster_sd = round(sd(SIZE),2),
    sample_size = length(SIZE)
  )

Table2017 <- kable(lobster_size_summary2017, col.names= c("Site", "Mean Lobster Size (mm)", "Standard Deviation of Size (mm)", "Abundance")) 
Table2017

lobster_size_col <- ggplot(lobster_size_summary2017, aes(x=SITE, y=lobster_mean)) +
  geom_col(aes(fill=SITE), show.legend=FALSE) +
  geom_errorbar(aes(ymax=lobster_mean+lobster_sd, ymin=lobster_mean-lobster_sd), width=0.2) +
  theme_classic() +
  labs(x="Site", y="Mean Lobster Size (mm)") +
  ggtitle("Lobster Size per Site (2017)") +
  geom_signif(y_position = c(98.0, 93.0), xmin = c(2,3), xmax = c(5,5), annotation = c("p = 0.023","p = 0.004"), tip_length = 0.1, size = 0.5, textsize = 3)


lobster_size_col

```



```{r, include=FALSE}
# 8 Creating dataframes for lobster size at each site in 2012 and 2017
lobster_NAPL_2012_17 <- lobster_size_edits %>%
  filter(YEAR=="2012" |YEAR=="2017", SITE=="NAPL") %>%
  as.data.frame() %>%
  expand.dft(freq="COUNT")

lobster_NAPL_2012 <- lobster_size_edits %>%
  filter(YEAR=="2012", SITE=="NAPL") %>%
  as.data.frame() %>%
  expand.dft(freq="COUNT")

lobster_NAPL_2017 <- lobster_size_edits %>%
  filter(YEAR=="2017", SITE=="NAPL") %>%
  as.data.frame() %>%
  expand.dft(freq="COUNT")

lobster_IVEE_2012_17 <- lobster_size_edits %>%
  filter(YEAR=="2012" |YEAR=="2017", SITE=="IVEE") %>%
  as.data.frame() %>%
  expand.dft(freq="COUNT")

lobster_IVEE_2012 <- lobster_size_edits %>%
  filter(YEAR=="2012", SITE=="IVEE") %>%
  as.data.frame() %>%
  expand.dft(freq="COUNT")

lobster_IVEE_2017 <- lobster_size_edits %>%
  filter(YEAR=="2017", SITE=="IVEE") %>%
  as.data.frame() %>%
  expand.dft(freq="COUNT")

lobster_AQUE_2012_17 <- lobster_size_edits %>%
  filter(YEAR=="2012" |YEAR=="2017", SITE=="AQUE") %>%
  as.data.frame() %>%
  expand.dft(freq="COUNT")

lobster_AQUE_2012 <- lobster_size_edits %>%
  filter(YEAR=="2012", SITE=="AQUE") %>%
  as.data.frame() %>%
  expand.dft(freq="COUNT")

lobster_AQUE_2017 <- lobster_size_edits %>%
  filter(YEAR=="2017", SITE=="AQUE") %>%
  as.data.frame() %>%
  expand.dft(freq="COUNT")

lobster_MOHK_2012_17 <- lobster_size_edits %>%
  filter(YEAR=="2012" |YEAR=="2017", SITE=="MOHK") %>%
  as.data.frame() %>%
  expand.dft(freq="COUNT")

lobster_MOHK_2012 <- lobster_size_edits %>%
  filter(YEAR=="2012", SITE=="MOHK") %>%
  as.data.frame() %>%
  expand.dft(freq="COUNT")

lobster_MOHK_2017 <- lobster_size_edits %>%
  filter(YEAR=="2017", SITE=="MOHK") %>%
  as.data.frame() %>%
  expand.dft(freq="COUNT")

lobster_CARP_2012_17 <- lobster_size_edits %>%
  filter(YEAR=="2012" |YEAR=="2017", SITE=="CARP") %>%
  as.data.frame() %>%
  expand.dft(freq="COUNT")

lobster_CARP_2012 <- lobster_size_edits %>%
  filter(YEAR=="2012", SITE=="CARP") %>%
  as.data.frame() %>%
  expand.dft(freq="COUNT")

lobster_CARP_2017 <- lobster_size_edits %>%
  filter(YEAR=="2017", SITE=="CARP") %>%
  as.data.frame() %>%
  expand.dft(freq="COUNT")
```

```{r, echo=FALSE}
#9 Running f and t tests to see if there is a difference in size at each site between 2012 and 2017

#Running F test for each of the sites
NAPL_ftest <- var.test(lobster_NAPL_2012$SIZE, lobster_NAPL_2017$SIZE)
NAPL_ftest

IVEE_ftest <- var.test(lobster_IVEE_2012$SIZE, lobster_IVEE_2017$SIZE)
IVEE_ftest

AQUE_ftest <- var.test(lobster_AQUE_2012$SIZE, lobster_AQUE_2017$SIZE)
AQUE_ftest

MOHK_ftest <- var.test(lobster_MOHK_2012$SIZE, lobster_MOHK_2017$SIZE)
MOHK_ftest

CARP_ftest <- var.test(lobster_CARP_2012$SIZE, lobster_CARP_2017$SIZE)
CARP_ftest

#Running t test for each of the sites
NAPL_ttest <- t.test(lobster_NAPL_2012$SIZE, lobster_NAPL_2017$SIZE, var.equal=TRUE)
NAPL_ttest

IVEE_ttest <- t.test(lobster_IVEE_2012$SIZE, lobster_IVEE_2017$SIZE, var.equal=TRUE)
IVEE_ttest

AQUE_ttest <- t.test(lobster_AQUE_2012$SIZE, lobster_AQUE_2017$SIZE, var.equal=TRUE)
AQUE_ttest

MOHK_ttest <- t.test(lobster_MOHK_2012$SIZE, lobster_MOHK_2017$SIZE, var.equal=TRUE)
MOHK_ttest

CARP_ttest <- t.test(lobster_CARP_2012$SIZE, lobster_CARP_2017$SIZE, var.equal=TRUE)
CARP_ttest

#there is a significant difference at the MOHK site, all the other sites are not significantly different


#Running cohen's d for effect size for each of the sites
NAPL_eff <- cohen.d(lobster_NAPL_2012$SIZE, lobster_NAPL_2017$SIZE)
NAPL_eff

IVEE_eff <- cohen.d(lobster_IVEE_2012$SIZE, lobster_IVEE_2017$SIZE)
IVEE_eff

AQUE_eff <- cohen.d(lobster_AQUE_2012$SIZE, lobster_AQUE_2017$SIZE)
AQUE_eff

MOHK_eff <- cohen.d(lobster_MOHK_2012$SIZE, lobster_MOHK_2017$SIZE)
MOHK_eff

CARP_eff <- cohen.d(lobster_CARP_2012$SIZE, lobster_CARP_2017$SIZE)
CARP_eff

```

```{r, echo=FALSE}
#Significance Tests between MPA and nonMPA
lobster_MPA_2012 <- lobster_size_edits %>%
  filter(YEAR=="2012", SITE=="NAPL" |SITE=="IVEE") %>%
  as.data.frame() %>%
  expand.dft(freq="COUNT")

lobster_MPA_2017 <- lobster_size_edits %>%
  filter(YEAR=="2017", SITE=="NAPL" |SITE=="IVEE") %>%
  as.data.frame() %>%
  expand.dft(freq="COUNT")

lobster_MPA_2012count <- lobster_size_edits %>%
  filter(YEAR=="2012", SITE=="NAPL" |SITE=="IVEE")

lobster_MPA_2017count <- lobster_size_edits %>%
  filter(YEAR=="2017", SITE=="NAPL" |SITE=="IVEE")

lobster_nonMPA_2012 <- lobster_size_edits %>%
  filter(YEAR=="2012", SITE=="MOHK" |SITE=="CARP" |SITE=="AQUE") %>%
  as.data.frame() %>%
  expand.dft(freq="COUNT")

lobster_nonMPA_2017 <- lobster_size_edits %>%
  filter(YEAR=="2017", SITE=="MOHK" |SITE=="CARP" |SITE=="AQUE") %>%
  as.data.frame() %>%
  expand.dft(freq="COUNT")

lobster_nonMPA_2012count <- lobster_size_edits %>%
  filter(YEAR=="2012", SITE=="MOHK" |SITE=="CARP" |SITE=="AQUE")

lobster_nonMPA_2017count <- lobster_size_edits %>%
  filter(YEAR=="2017", SITE=="MOHK" |SITE=="CARP" |SITE=="AQUE")

MPAvnonMPA2012_ftest <- var.test(lobster_MPA_2012$SIZE, lobster_nonMPA_2012$SIZE)
MPAvnonMPA2012_ftest

MPAvnonMPA2017_ftest <- var.test(lobster_MPA_2017$SIZE, lobster_nonMPA_2017$SIZE)
MPAvnonMPA2017_ftest
#Variences are not significantly different between nonmpa and mpa in 2012 but they are in 2017 for size

MPAvnonMPA2012count_ftest <- var.test(lobster_MPA_2012count$COUNT, lobster_nonMPA_2012count$COUNT)
MPAvnonMPA2012count_ftest

MPAvnonMPA2017count_ftest <- var.test(lobster_MPA_2017count$COUNT, lobster_nonMPA_2017count$COUNT)
MPAvnonMPA2017count_ftest
#Variences are significantly different in both 2012 and 2017 in terms of count

MPAvnonMPA2012_ttest <- t.test(lobster_MPA_2012$SIZE, lobster_nonMPA_2012$SIZE, var.equal=TRUE)
MPAvnonMPA2012_ttest

MPAvnonMPA2017_ttest <- t.test(lobster_MPA_2017$SIZE, lobster_nonMPA_2017$SIZE)
MPAvnonMPA2017_ttest
#There is a significant difference in mean size between mpa and nonmpa site in 2012, there is not a significant difference in 2017

MPAvnonMPA2012count_ttest <- t.test(lobster_MPA_2012count$COUNT, lobster_nonMPA_2012count$COUNT)
MPAvnonMPA2012count_ttest

MPAvnonMPA2017count_ttest <- t.test(lobster_MPA_2017count$COUNT, lobster_nonMPA_2017count$COUNT)
MPAvnonMPA2017count_ttest

#In terms of count there is a significant difference between mpa and nonmpa size in both 2012 and 2017

MPAvnonMPA2012_eff <- cohen.d(lobster_MPA_2012$SIZE, lobster_nonMPA_2012$SIZE)
MPAvnonMPA2012_eff

MPAvnonMPA2017_eff <- cohen.d(lobster_MPA_2017$SIZE, lobster_nonMPA_2017$SIZE)
MPAvnonMPA2017_eff

MPAvnonMPA2012count_eff <- cohen.d(lobster_MPA_2012count$COUNT, lobster_nonMPA_2012count$COUNT)
MPAvnonMPA2012count_eff

MPAvnonMPA2017count_eff <- cohen.d(lobster_MPA_2017count$COUNT, lobster_nonMPA_2017count$COUNT)
MPAvnonMPA2017count_eff

```


```{r, include=FALSE}
#10 Create a data frame showing if lobsters are above the legal format or not

#Make table of lobsters above the legal size with yes for above and no for not above

lobster_legal <- lobster_case_format2017 %>%
  mutate(legal = ifelse(SIZE > 86.2, "YES", "NO")) %>%
  count(SITE, legal) %>%
  spread(legal, n) %>%
  select(-SITE)
#Yes means the lobster is of legal size, no means the lobster is not legal size

rownames(lobster_legal) <- c("AQUE", "CARP", "IVEE", "MOHK", "NAPL")
  
  
```

```{r, echo=FALSE}
#11 Get Propoprtions for each of the sites

lobster_legal_prop <- round(prop.table(as.matrix(lobster_legal), 1), 3)
#creates prop table show the proportion of legal lobsters at each site

lobster_x2 <- chisq.test(lobster_legal)
lobster_x2 #Running a chi square test

#there is a significant difference between the site in terms of legal lobster size
```

